# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

LEP <- function(Xs, y, SS = NULL, opts = NULL, logfile = "screen", lbPval = 1e-12, verbose = FALSE, memory_copy = TRUE) {
    .Call('_LEP_LEP', PACKAGE = 'LEP', Xs, y, SS, opts, logfile, lbPval, verbose, memory_copy)
}

LEPCV <- function(Xs, y, SS = NULL, opts = NULL, logfile = "screen", lbPval = 1e-12, measure = "mse", verbose = FALSE) {
    .Call('_LEP_LEPCV', PACKAGE = 'LEP', Xs, y, SS, opts, logfile, lbPval, measure, verbose)
}

LEP_Plink <- function(genoplinkfile, SS = NULL, opts = NULL, logfile = "screen", lbPval = 1e-12, verbose = FALSE) {
    .Call('_LEP_LEP_Plink', PACKAGE = 'LEP', genoplinkfile, SS, opts, logfile, lbPval, verbose)
}

LEPCV_Plink <- function(genoplinkfile, SS = NULL, opts = NULL, logfile = "screen", lbPval = 1e-12, measure = "mse", verbose = FALSE) {
    .Call('_LEP_LEPCV_Plink', PACKAGE = 'LEP', genoplinkfile, SS, opts, logfile, lbPval, measure, verbose)
}

Predict <- function(fit_, X) {
    .Call('_LEP_Predict', PACKAGE = 'LEP', fit_, X)
}

